server:
  port: 8082
  servlet:
    context-path: /study
spring:
  profiles:
    active: develope
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/study
    username: study
    password: study
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  redis:
    host: localhost
    port: 6379 
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    test-queue-name: hello
mybatis:
  config-location: classpath:mybatis/configuration.xml
      